# Generated by Django 4.1 on 2022-10-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=25)),
                ('patient_phono', models.IntegerField(max_length=10)),
                ('patient_age', models.IntegerField(max_length=2)),
                ('patient_problm', models.TextField(max_length=100)),
                ('patient_dob', models.DateField()),
            ],
        ),
    ]
